### PR TITLE
fix: store URLs in environment to avoid issues with long filenames

### LINKED ISSUE #1046: Issue with reading from long urls
Hi all,

It looks like there is an issue in reading from urls that are too long. 

``` r
library(s3fs)
library(polars)


# NOTE: Create temporary file
tmp_file <- tempfile()

pl$DataFrame(
  col1 = sample(0:100, 200, replace = T),
  col2 = sample(c(letters, LETTERS), 200, replace = T)
)$write_csv(tmp_file)


# Will use minio for demo purposes
s3_file_system(profile_name = "minio", signature_version = "s3v4")

bucket <- s3_path("test-bucket")
dstpth <- s3_path(bucket, "test/demo.csv")

s3_bucket_create(bucket)
#> [1] "s3://test-bucket"
s3_file_upload(path = tmp_file, new_path = dstpth, overwrite = T)
#> [1] "s3://test-bucket/test/demo.csv"

obj <- s3fs::s3_file_url(dstpth)

pl$read_csv(obj)
#> Warning in download.file(url = actual_url, destfile = tmp_file): URL
#> http://127.0.0.1:9000/test-bucket/test/demo.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240416T134113Z&X-Amz-Expires=3600&X-Amz-Signature=997b021a91547c844fa948989b6a4ef16fada444e19e62c781420fe92aad198f&X-Amz-SignedHeaders=host:
#> cannot open destfile
#> '/var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//RtmpYpd5jt/http...127.0.0.1.9000.test.bucket.test.demo.csv.X.Amz.Algorithm.AWS4.HMAC.SHA256.X.Amz.Credential.minioadmin.2F20240416.2Fus.east.1.2Fs3.2Faws4_request.X.Amz.Date.20240416T134113Z.X.Amz.Expires.3600.X.Amz.Signature.997b021a91547c844fa948989b6a4ef16fada444e19e62c781420fe92aad198f.X.Amz.SignedHeaders.host',
#> reason 'File name too long'
#> Warning in download.file(url = actual_url, destfile = tmp_file): download had
#> nonzero exit status
#> tmp file placed in 
#>  /var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//RtmpYpd5jt/http...127.0.0.1.9000.test.bucket.test.demo.csv.X.Amz.Algorithm.AWS4.HMAC.SHA256.X.Amz.Credential.minioadmin.2F20240416.2Fus.east.1.2Fs3.2Faws4_request.X.Amz.Date.20240416T134113Z.X.Amz.Expires.3600.X.Amz.Signature.997b021a91547c844fa948989b6a4ef16fada444e19e62c781420fe92aad198f.X.Amz.SignedHeaders.host
#> Error: Execution halted with the following contexts
#>    0: In R: in pl$read_csv():
#>    0: During function call [base::tryCatch(base::withCallingHandlers({
#>           NULL
#>           base::saveRDS(base::do.call(base::do.call, base::c(base::readRDS("/var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//Rtmpa6BQxU/callr-fun-f17f59614721"), 
#>               base::list(envir = .GlobalEnv, quote = TRUE)), envir = .GlobalEnv, 
#>               quote = TRUE), file = "/var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//Rtmpa6BQxU/callr-res-f17f184f55f", 
#>               compress = FALSE)
#>           base::flush(base::stdout())
#>           base::flush(base::stderr())
#>           NULL
#>           base::invisible()
#>       }, error = function(e) {
#>           {
#>               callr_data <- base::as.environment("tools:callr")$`__callr_data__`
#>               err <- callr_data$err
#>               if (FALSE) {
#>                   base::assign(".Traceback", base::.traceback(4), envir = callr_data)
#>                   utils::dump.frames("__callr_dump__")
#>                   base::assign(".Last.dump", .GlobalEnv$`__callr_dump__`, 
#>                       envir = callr_data)
#>                   base::rm("__callr_dump__", envir = .GlobalEnv)
#>               }
#>               e <- err$process_call(e)
#>               e2 <- err$new_error("error in callr subprocess")
#>               class <- base::class
#>               class(e2) <- base::c("callr_remote_error", class(e2))
#>               e2 <- err$add_trace_back(e2)
#>               cut <- base::which(e2$trace$scope == "global")[1]
#>               if (!base::is.na(cut)) {
#>                   e2$trace <- e2$trace[-(1:cut), ]
#>               }
#>               base::saveRDS(base::list("error", e2, e), file = base::paste0("/var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//Rtmpa6BQxU/callr-res-f17f184f55f", 
#>                   ".error"))
#>           }
#>       }, interrupt = function(e) {
#>           {
#>               callr_data <- base::as.environment("tools:callr")$`__callr_data__`
#>               err <- callr_data$err
#>               if (FALSE) {
#>                   base::assign(".Traceback", base::.traceback(4), envir = callr_data)
#>                   utils::dump.frames("__callr_dump__")
#>                   base::assign(".Last.dump", .GlobalEnv$`__callr_dump__`, 
#>                       envir = callr_data)
#>                   base::rm("__callr_dump__", envir = .GlobalEnv)
#>               }
#>               e <- err$process_call(e)
#>               e2 <- err$new_error("error in callr subprocess")
#>               class <- base::class
#>               class(e2) <- base::c("callr_remote_error", class(e2))
#>               e2 <- err$add_trace_back(e2)
#>               cut <- base::which(e2$trace$scope == "global")[1]
#>               if (!base::is.na(cut)) {
#>                   e2$trace <- e2$trace[-(1:cut), ]
#>               }
#>               base::saveRDS(base::list("error", e2, e), file = base::paste0("/var/folders/sp/scbzkbwx6hbchmylsx0y52k80000gn/T//Rtmpa6BQxU/callr-res-f17f184f55f", 
#>                   ".error"))
#>           }
#>       }, callr_message = function(e) {
#>           base::try(base::signalCondition(e))
#>       }), error = function(e) {
#>           NULL
#>           if (FALSE) {
#>               base::try(base::stop(e))
#>           }
#>           else {
#>               base::invisible()
#>           }
#>       }, interrupt = function(e) {
#>           NULL
#>           if (FALSE) {
#>               e
#>           }
#>           else {
#>               base::invisible()
#>           }
#>       })]
#>    1: Encountered the following error in Rust-Polars:
#>          File name too long (os error 63): ...97b021a91547c844fa948989b6a4ef16fada444e19e62c781420fe92aad198f.X.Amz.SignedHeaders.host
```

<sup>Created on 2024-04-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by DyfanJones**
Fixes #1046

### CODE REVIEW

File: R/io_csv.R [hunk 1]
```diff
@@ -134,7 +134,9 @@ pl_scan_csv = function(
         return(RPolarsRNullValues$new_named(unlist(null_values)))
       }
 
-      stop("null_values arg must be a string OR unamed char vec OR named char vec")
+      Err_plain(
+        "null_values arg must be a string OR unamed char vec OR named char vec"
+      ) |> unwrap()
```
Comment (eitsupi) [inline R/io_csv.R:139]: Could you use `unwrap()` with the context argument?
Patterns used elsewhere in the package, such as:

```r
uw = function(res) unwrap(" in pl$scan_csv():")
```

File: tests/testthat/test-csv-read.R [hunk 2]
```diff
@@ -181,3 +181,18 @@ test_that("bad paths", {
     "failed to locate file"
   )
 })
+
+test_that("cache url tempfile", {
+  url <- "https://vincentarelbundock.github.io/Rdatasets/csv/AER/BenderlyZwick.csv"
```
Comment (eitsupi) [inline tests/testthat/test-csv-read.R:186]: Please check the website status with `testthat::skip_if_offline()` <https://testthat.r-lib.org/reference/skip.html>

**Review by eitsupi — CHANGES_REQUESTED** [review]

File: R/io_csv.R (hunk 1 above)
Comment (DyfanJones) [reply R/io_csv.R:139]: Sure thing. What about the internal functions i.e. `check_is_link` are you happy with `unwrap("in check_is_link():")` or should this be left alone as it is internal and not exported to the user.

File: tests/testthat/test-csv-read.R [hunk 3]
```diff
@@ -181,3 +181,18 @@ test_that("bad paths", {
...
+  local_mocked_bindings(
+    download.file = function(...) invisible(NULL),
+  )
+  check_is_link(url, reuse_downloaded = T)
```
Comment (etiennebacher) [inline tests/testthat/test-csv-read.R:190]: Can you replace `T` by `TRUE`?

File: R/io_csv.R (hunk 1 above)
Comment (etiennebacher) [reply R/io_csv.R:139]: For internal functions like `check_is_link()`, you can leave `unwrap()` as is. This is what we do for other internal functions

**Review by etiennebacher — COMMENTED** [review]
Thanks @DyfanJones, can you also add a bullet point in NEWS in a "Bug fixes" category?

File: NEWS.md [hunk 4]
```diff
@@ -5,6 +5,7 @@
 ### Bug fixes
 
 * `$len()` now correctly includes `null` values in the count (#1044).
+* cache temporary file name for url file download (#1046)
```
Comment (etiennebacher) [inline NEWS.md:8]:
```suggestion
* In some read/scan functions on Windows, downloading files could fail if the URL was too long. This is now fixed (#1049).
```
The NEWS item should mention the problem solved rather than the solution employed. I took the liberty of adding the OS because I think this is a windows-specific issue but you can remove that if the problem occurred on another OS for you.

File: R/io_csv.R [hunk 5]
```diff
@@ -134,7 +134,9 @@ pl_scan_csv = function(
         return(RPolarsRNullValues$new_named(unlist(null_values)))
       }
 
-      stop("null_values arg must be a string OR unamed char vec OR named char vec")
+      Err_plain(
+        "null_values arg must be a string OR unamed char vec OR named char vec"
+      ) |> unwrap(" in pl$scan_csv():")
```
Comment (etiennebacher) [inline R/io_csv.R:139]:
```suggestion
      ) |> unwrap("in pl$scan_csv():")
```

**Review by etiennebacher — CHANGES_REQUESTED** [review]
Thanks, I just have a couple of minor comments and the conflict needs to be resolved, but after that I'm ok to merge

File: NEWS.md (hunk 4 above)
Comment (etiennebacher) [reply NEWS.md:8]: Thanks for the info, I edited the title and the suggested change

Comment (DyfanJones) [reply NEWS.md]: Ah my bad for being too eager and not refreshing my browser 😆

**Review by etiennebacher — APPROVED** [review]
Thanks!

**Review by eitsupi — APPROVED** [review]
Thanks!
