### PR TITLE
fix: Keeps Enum order when converting to R

### LINKED ISSUE #1251: Keep Enum order when convertir to R dataframe
When converting an enum series from Polars to R, the order is not always kept.

### PR DESCRIPTION
**Pull request by andyquinterom**
Closes #1251

### CODE REVIEW

**Comment by etiennebacher** [comment]
Hi, thanks for opening the issue and the corresponding PR, can you add a test and a bullet point in NEWS?

**Comment by andyquinterom** [comment]
@etiennebacher I added a test to validate many cases. 

```r
  # Generate 100 random data frames with random
  # orders for levels. They should always match
  for (i in 1:100) {
    expected_levels = sample(letters, length(letters))
    expected_values = sample(letters, length(letters))
    expect_identical(
      as_polars_series(expected_values)$
        cast(pl$Enum(expected_levels))$
        to_r(),
      factor(expected_values, levels = expected_levels)
    )
  }
  ```

**Comment by andyquinterom** [comment]
@etiennebacher Everything seems to pass except for R CMD check due to Non-api calls, but I think that's out of the scope of this pull request

File: tests/testthat/test-datatype.R [hunk 1]
```diff
@@ -224,12 +224,18 @@ test_that("contains_* functions for datatype work", {
...
 
 test_that("Enum", {
-  expect_identical(
-    as_polars_series(c("z", "z", "k", "a"))$
-      cast(pl$Enum(c("z", "k", "a")))$
-      to_r(),
-    factor(c("z", "z", "k", "a"))
-  )
+  # Generate 100 random data frames with random
+  # orders for levels. They should always match
```
Comment (eitsupi) [inline tests/testthat/test-datatype.R:228]: Please use quickcheck or patrick instead of for loop.
https://www.etiennebacher.com/posts/2024-10-01-using-property-testing-in-r/

**Review by eitsupi — CHANGES_REQUESTED** [review]

**Comment by etiennebacher** [comment]
> Everything seems to pass except for R CMD check due to Non-api calls, but I think that's out of the scope of this pull request

Yes this is out of scope. I agree with @eitsupi about using property-based testing on this. I think something like this would do the job (but I haven't tested yet):

```r
test_that("reversing twice returns the original input", {
  for_all(
    values = any_atomic(any_na = TRUE),
	levels = any_atomic(any_na = TRUE),
    property = function(values, levels) {
	    expect_identical(
	      as_polars_series(values)$
	        cast(pl$Enum(levels))$
	        to_r(),
	      factor(values, levels = levels)
	    )
    }
  )
})
``` 
Please also add a bullet point in news with the PR number and your username (if you want).

File: DESCRIPTION [hunk 2]
```diff
@@ -116,7 +117,7 @@ Collate:
     'sql.R'
     'vctrs.R'
     'zzz.R'
-Config/rextendr/version: 0.3.1
+Config/rextendr/version: 0.3.1.9000
```
Comment (eitsupi) [inline DESCRIPTION:120]: Unrelated change.

File: NEWS.md [hunk 3]
```diff
@@ -5,6 +5,7 @@
 ## Polars R Package 0.20.0
 
 - Updated rust-polars to 0.43.1 (#1230).
+- Maintains level order when converting Enums to factors (#1252, @andyquinterom)
```
Comment (eitsupi) [inline NEWS.md:8]: I think you are adding it in the wrong place.

**Review by eitsupi — CHANGES_REQUESTED** [review]
Thanks for the updates!

Could you bump the Rust lib version and please remove the lib-sums.tsv.
Please check the document for details.
https://github.com/pola-rs/r-polars/blob/8ecb1a358c5bf0c6c6e6c9527904bb798f07a101/DEVELOPMENT.md

File: NEWS.md (hunk 3 above)
Comment (andyquinterom) [reply NEWS.md]: Thanks for pointing this out

File: DESCRIPTION (hunk 2 above)
Comment (andyquinterom) [reply DESCRIPTION]: Done

**Comment by andyquinterom** [comment]
> Thanks for the updates!
> 
> Could you bump the Rust lib version and please remove the lib-sums.tsv. Please check the document for details. https://github.com/pola-rs/r-polars/blob/8ecb1a358c5bf0c6c6e6c9527904bb798f07a101/DEVELOPMENT.md

I just ran the task and see that nothing has changed. Am I doing something wrong?

**Comment by eitsupi** [comment]
We should update lib version by hand first.
https://github.com/pola-rs/r-polars/blob/main/src%2Frust%2FCargo.toml#L3-L3

**Review by etiennebacher — APPROVED** [review]
Thanks @andyquinterom

File: tests/testthat/test-datatype.R [hunk 4]
```diff
@@ -224,11 +224,16 @@ test_that("contains_* functions for datatype work", {
 })
 
 test_that("Enum", {
-  expect_identical(
-    as_polars_series(c("z", "z", "k", "a"))$
-      cast(pl$Enum(c("z", "k", "a")))$
-      to_r(),
-    factor(c("z", "z", "k", "a"))
+  quickcheck::for_all(
+    factors = quickcheck::factor_(),
```
Comment (eitsupi) [inline tests/testthat/test-datatype.R:228]: How about including `NA`?

File: src/rust/Cargo.toml [hunk 5]
```diff
@@ -1,6 +1,6 @@
 [package]
 name = "r-polars"
-version = "0.43.0"
+version = "0.44.0"
```
Comment (eitsupi) [inline src/rust/Cargo.toml:3]:
```suggestion
version = "0.43.1"
```

File: DESCRIPTION [hunk 6]
```diff
@@ -118,5 +119,5 @@ Collate:
     'zzz.R'
 Config/rextendr/version: 0.3.1
 VignetteBuilder: knitr
-Config/polars/LibVersion: 0.43.0
+Config/polars/LibVersion: 0.44.0
```
Comment (eitsupi) [inline DESCRIPTION:122]:
```suggestion
Config/polars/LibVersion: 0.43.1
```

**Review by eitsupi — CHANGES_REQUESTED** [review]
Almost looks good.
A few comments.

File: tests/testthat/test-datatype.R (hunk 4 above)
Comment (eitsupi) [reply tests/testthat/test-datatype.R:228]: I tried but there is an issue about that.
armcn/quickcheck#22

**Review by eitsupi — APPROVED** [review]
Thanks!
